# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0019_auto_20171024_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateBookTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='candidate.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False)),
                ('exam_type', models.CharField(choices=[('MOH', 'MOH'), ('Prometric/HAAD', 'Prometric/HAAD')], default='MOH', max_length=100)),
                ('name', models.CharField(default='Exam1', max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(default='Room1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('maximum_number_of_students', models.IntegerField(default=200)),
                ('number_of_students_booked', models.IntegerField(default=0, editable=False)),
                ('exam', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='examroom',
            name='exam_time_slot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_time_slot', to='exam.ExamTimeSlot'),
        ),
        migrations.AddField(
            model_name='candidatebooktimeslot',
            name='exam_room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_room', to='exam.ExamRoom'),
        ),
        migrations.AddField(
            model_name='candidatebooktimeslot',
            name='time_slot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='exam.ExamTimeSlot'),
        ),
    ]
