# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebooktimeslot',
            name='exam',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_book_slot', to='exam.Exam'),
        ),
    ]
