# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_candidatebooktimeslot_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebooktimeslot',
            name='hall_ticket_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
