# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_candidatebooktimeslot_hall_ticket_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='hall_ticket_download_minimum_number_of_days',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
