# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_hall_ticket_download_minimum_number_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Written + Interview', 'Written + Interview'), ('Only Interview', 'Only Interview')], default='Only Interview', max_length=100),
        ),
    ]
