# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 17:46
from __future__ import unicode_literals

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20171116_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=hashid_field.field.HashidAutoField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, min_length=7, primary_key=True, serialize=False),
        ),
    ]
