# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0023_auto_20171220_0851'),
        ('exam', '0010_auto_20171121_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='employer.Advertisement'),
        ),
    ]
