# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-12 13:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20170812_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(verbose_name=datetime.datetime(2017, 8, 12, 13, 24, 29, 40477, tzinfo=utc)),
        ),
    ]
