# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20170812_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date_of_birth',
            field=models.DateField(verbose_name=datetime.datetime(2017, 8, 29, 9, 58, 51, 946219, tzinfo=utc)),
        ),
    ]
