# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_employer_registration_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employer',
            name='registration_certification',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
