# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employer', '0003_auto_20170801_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='registration_certification',
        ),
        migrations.AddField(
            model_name='employer',
            name='company_username',
            field=models.ForeignKey(default='Employer1', on_delete=django.db.models.deletion.CASCADE, related_name='company_username', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company',
            field=models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], max_length=200),
        ),
    ]
