# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_remove_employer_company_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='registration_certification',
            field=models.CharField(default='', max_length=200),
        ),
    ]
