# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 06:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_auto_20170801_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_username', to=settings.AUTH_USER_MODEL),
        ),
    ]
