# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_auto_20170801_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_username',
        ),
        migrations.AddField(
            model_name='employer',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
    ]
