# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0011_auto_20170801_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_id',
        ),
    ]
