# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='instructor_id',
            new_name='topic_id',
        ),
    ]
