# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_auto_20180405_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(default='Topic One', max_length=200, unique=True),
        ),
    ]
