# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20180405_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('question_bank_id', hashid_field.field.HashidAutoField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Question Bank One', max_length=200, unique=True)),
                ('questions', models.ManyToManyField(to='instructor.Question')),
            ],
        ),
    ]
