# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_phone'),
        ('instructor', '0005_questionbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', hashid_field.field.HashidAutoField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Question Bank One', max_length=200, unique=True)),
                ('date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('duration', models.IntegerField(default=30)),
                ('students', models.ManyToManyField(to='student.Student')),
            ],
        ),
    ]
