# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0006_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='Exam One', max_length=200, unique=True),
        ),
    ]
