# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_exam_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
