# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Indian', 'Indian'), ('Foreign', 'Foreign')], default='Indian', max_length=200)),
                ('employer_name', models.CharField(choices=[('Indian', 'Indian'), ('Foreign', 'Foreign')], default='Employer Name', max_length=200)),
                ('employer_registration', models.CharField(default='ABC-1234', max_length=200)),
                ('employer_type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], default='Private', max_length=200)),
                ('authorized_signatory', models.CharField(default='Auth 123', max_length=200)),
                ('sector', models.CharField(choices=[('Health', 'Health'), ('Construction', 'Construction'), ('IT', 'IT'), ('Shipping', 'Shipping')], default='Health', max_length=200)),
                ('address', models.CharField(default='abcdef', max_length=500)),
                ('website', models.URLField(default='http://example.com')),
                ('phone', models.CharField(default='9810117638', max_length=200)),
                ('registration_certification', models.FileField(default='', upload_to='')),
                ('authorized_signatory_id_proof', models.FileField(default=None, upload_to='')),
                ('total_employees', models.IntegerField(default=0)),
                ('annual_recruitment_of_indians', models.IntegerField(default=0)),
                ('nurses_degree', models.IntegerField(default=0)),
                ('nurses_diploma', models.IntegerField(default=0)),
                ('doctors', models.IntegerField(default=0)),
                ('lab_technicians', models.IntegerField(default=0)),
                ('pathologists', models.IntegerField(default=0)),
                ('employer_username', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(max_length=40)),
                ('key_expires', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
