# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Indian', 'Indian'), ('Foreign', 'Foreign')], max_length=200)),
                ('company', models.CharField(default='', max_length=200)),
                ('company_registration', models.CharField(max_length=200)),
                ('company_type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], max_length=200)),
                ('sector', models.CharField(choices=[('Health', 'Health'), ('Construction', 'Construction'), ('IT', 'IT'), ('Shipping', 'Shipping')], max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('website', models.URLField()),
                ('phone', models.CharField(max_length=200)),
                ('registration_certification', models.FileField(default='', upload_to='')),
                ('approved', models.BooleanField()),
            ],
        ),
    ]
