# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(default='Nurse', max_length=200)),
                ('closing_date', models.DateField(default=django.utils.timezone.now)),
                ('number_of_vacancies', models.IntegerField(default=5)),
                ('educational_qualifications', models.CharField(default='ANM required', max_length=500)),
                ('eligibility_tests', models.CharField(choices=[('Prometric (Saudi Arabia)', 'Prometric (Saudi Arabia)'), ('Prometric (UAE)', 'Prometric (UAE)'), ('Prometric (Qatar)', 'Prometric (Qatar)'), ('HAAD', 'HAAD'), ('DHA', 'DHA'), ('IELTS', 'IELTS'), ('CGFNS', 'CGFNS'), ('TOEFL', 'TOEFL'), ('OET', 'OET'), ('Other', 'Other')], default='HAAD', max_length=500)),
            ],
        ),
    ]
