# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 16:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='city',
            field=models.CharField(default='Delhi', max_length=200),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='country',
            field=models.CharField(default='India', max_length=200),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='experience',
            field=models.CharField(default='2 years', max_length=500),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='name_of_hospital',
            field=models.CharField(default='Hospital1', max_length=200),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='closing_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 25, 16, 50, 26, 522439, tzinfo=utc)),
        ),
    ]
