# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_employer_company_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_username',
        ),
    ]
