# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_auto_20170925_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_uuid',
            field=models.CharField(editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='closing_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 25, 17, 36, 45, 193946, tzinfo=utc)),
        ),
    ]
