# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_auto_20170801_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='annual_recruitment_of_indians',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='authorized_signatory_id_proof',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='employer',
            name='doctors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='lab_technician',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='nurses_degree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='nurses_diploma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='pathologist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='profession',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='employer',
            name='total_employees',
            field=models.IntegerField(default=0),
        ),
    ]
