# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 14:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_auto_20170925_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='employer',
            new_name='employer_advert',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='closing_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 26, 14, 43, 7, 733265, tzinfo=utc)),
        ),
    ]
