# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_remove_employer_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='lab_technician',
            new_name='lab_technicians',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='pathologist',
            new_name='pathologists',
        ),
    ]
