# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-18 07:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_auto_20170926_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='duration_of_assignment_number',
            new_name='duration_of_assignment',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='salary_units',
            new_name='salary_currency',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='accomodation_allowance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='accomodation_allowance_currency',
            field=models.CharField(default='AED', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='life_insurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='life_insurance_currency',
            field=models.CharField(default='AED', max_length=20),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='maternity_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='closing_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 17, 7, 19, 33, 235938, tzinfo=utc)),
        ),
    ]
