# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_auto_20170801_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='profession',
        ),
    ]
