# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0013_auto_20171023_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='closing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
