# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import tnai.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0014_auto_20171023_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='authorized_signatory_id_proof',
            field=models.FileField(default=None, upload_to='', validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='registration_certification',
            field=models.FileField(default='', upload_to='', validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
    ]
