# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import tnai.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0015_auto_20171120_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='annual_recruitment_of_indians',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='authorized_signatory_id_proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='doctors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='lab_technicians',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='nurses_degree',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='nurses_diploma',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='pathologists',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='registration_certification',
            field=models.FileField(blank=True, default='', null=True, upload_to='', validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='total_employees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
