# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0016_auto_20171129_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_name',
            field=models.CharField(default='Employer Name', max_length=200),
        ),
    ]
