# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0017_auto_20171129_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='employer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='employer_registration',
            new_name='registration',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='employer_type',
            new_name='type',
        ),
    ]
