# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 13:45
from __future__ import unicode_literals

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0018_auto_20171129_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='ad_uuid',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='obfucated_id',
            field=hashid_field.field.HashidField(alphabet='0123456789ABCDEF', editable=False, min_length=7, null=True),
        ),
    ]
