# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0019_auto_20171129_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='obfucated_id',
            new_name='obfuscated_id',
        ),
    ]
