# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0020_auto_20171129_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='eligibility_tests',
            field=models.CharField(choices=[('Prometric (Saudi Arabia)', 'Prometric (Saudi Arabia)'), ('Prometric (Oman)', 'Prometric (Oman)'), ('Prometric (Qatar)', 'Prometric (Qatar)'), ('HAAD', 'HAAD'), ('DHA', 'DHA'), ('IELTS', 'IELTS'), ('CGFNS', 'CGFNS'), ('TOEFL', 'TOEFL'), ('OET', 'OET'), ('Other', 'Other')], default='HAAD', max_length=500),
        ),
    ]
