# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0022_advertisement_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='is_provisional_registration_number',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='registration_number',
            field=hashid_field.field.HashidField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', default=None, editable=False, min_length=7, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='sent_email_notification_provisional_registration_number',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
