# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0023_auto_20171220_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='maternity_leave',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='maternity_leave_number_of_days',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
