# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0025_auto_20180410_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='dummy_employer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='accomodation_allowance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='accomodation_allowance_currency',
            field=models.CharField(blank=True, default='AED', max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.CharField(blank=True, default='Delhi', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='closing_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='duration_of_assignment',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='duration_of_assignment_units',
            field=models.CharField(blank=True, choices=[('Days', 'Days'), ('Weeks', 'Weeks'), ('Months', 'Months'), ('Years', 'Years')], default='Months', max_length=15),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='educational_qualifications',
            field=models.CharField(blank=True, default='ANM required', max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='eligibility_tests',
            field=models.CharField(blank=True, choices=[('Prometric (Saudi Arabia)', 'Prometric (Saudi Arabia)'), ('Prometric (Oman)', 'Prometric (Oman)'), ('Prometric (Qatar)', 'Prometric (Qatar)'), ('HAAD', 'HAAD'), ('DHA', 'DHA'), ('IELTS', 'IELTS'), ('CGFNS', 'CGFNS'), ('TOEFL', 'TOEFL'), ('OET', 'OET'), ('Other', 'Other')], default='HAAD', max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='experience',
            field=models.CharField(blank=True, default='2 years', max_length=500),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='gender',
            field=models.CharField(blank=True, choices=[('Any', 'Any'), ('Male', 'Male'), ('Female', 'Female')], default='Any', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='job_role',
            field=models.CharField(blank=True, default='Nurse', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='life_insurance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='life_insurance_currency',
            field=models.CharField(blank=True, default='AED', max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name_of_hospital',
            field=models.CharField(blank=True, default='Hospital1', max_length=200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='number_of_vacancies',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='salary_currency',
            field=models.CharField(blank=True, default='AED', max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='salary_number',
            field=models.IntegerField(blank=True, default=1200),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
