# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0026_auto_20180814_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='employer_advert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_advert', to='employer.Employer'),
        ),
    ]
