# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-07 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='degree_recognized_by_INC',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='state_nursing_council_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='state_nursing_council_proof',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='state_nursing_council_registration_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='state_nursing_council_registration_number',
        ),
    ]
