# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 12:23
from __future__ import unicode_literals

import candidate.models
from django.db import migrations, models
import tnai.validators


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_auto_20180410_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum_vitae',
            field=models.FileField(blank=True, default=None, max_length=500, null=True, upload_to=candidate.models.Candidate.media_path, validators=[tnai.validators.ValidateFileExtension.validate_file_doc_or_pdf]),
        ),
    ]
