# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate', '0003_auto_20170830_0820'),
    ]

    operations = [
#        migrations.RemoveField(
#            model_name='candidate',
#            name='candidate_username',
#        ),
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('----', '----'), ('10th', '10th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Postgraduate', 'Postgraduate'), ('M. Phil', 'M. Phil'), ('PhD', 'PhD')], default='----', max_length=200)),
                ('year', models.PositiveSmallIntegerField(choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('institute_name', models.CharField(default='Institute', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='address_line_1',
            field=models.CharField(default='Address Line 1', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='address_line_2',
            field=models.CharField(default='Address Line 2', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='candidate_username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_username', to=settings.AUTH_USER_MODEL, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='degree_recognized_by_INC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state_nursing_council',
            field=models.CharField(choices=[('SNC1', 'SNC1'), ('SNC2', 'SNC2'), ('SNC3', 'SNC3')], default='SNC1', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state_nursing_council_proof',
            field=models.FileField(default=None, upload_to='', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state_nursing_council_registration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidate',
            name='state_nursing_council_registration_number',
            field=models.CharField(default='SNC Registration Number', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tnai_number',
            field=models.CharField(default='TNAI number', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='district',
            field=models.CharField(choices=[('District1', 'District1'), ('District2', 'District2')], default='District1', max_length=200),
        ),
        migrations.AddField(
            model_name='educationalqualification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate'),
        ),
    ]
