# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_auto_20170907_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='curriculum_vitae',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photograph',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
