# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 11:32
from __future__ import unicode_literals

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20170908_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum_vitae',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Candidate.media_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photograph',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=candidate.models.Candidate.media_path),
        ),
    ]
