# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-08 11:50
from __future__ import unicode_literals

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20170908_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalqualifications',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Qualifications.media_path),
        ),
        migrations.AlterField(
            model_name='educationalqualifications',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Qualifications.media_path),
        ),
        migrations.AlterField(
            model_name='eligibilitytests',
            name='eligibility_proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.EligibilityTests.media_path),
        ),
        migrations.AlterField(
            model_name='experience',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Experience.media_path),
        ),
        migrations.AlterField(
            model_name='professionalqualifications',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Qualifications.media_path),
        ),
    ]
