# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20170831_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='state_nursing_council',
            new_name='state_nursing_council_name',
        ),
    ]
