# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20170908_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalqualifications',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='educationalqualifications',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='professionalqualifications',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
