# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_auto_20170831_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalqualification',
            name='qualification_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state_nursing_council_name',
            field=models.CharField(blank=True, choices=[('SNC1', 'SNC1'), ('SNC2', 'SNC2'), ('SNC3', 'SNC3')], default='SNC1', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state_nursing_council_registration_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state_nursing_council_registration_number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='educationalqualification',
            name='institute_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='educationalqualification',
            name='percentage',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='educationalqualification',
            name='qualification',
            field=models.CharField(blank=True, choices=[('----', '----'), ('10th', '10th'), ('12th', '12th'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Postgraduate', 'Postgraduate'), ('M. Phil', 'M. Phil'), ('PhD', 'PhD')], default='----', max_length=200),
        ),
        migrations.AlterField(
            model_name='educationalqualification',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017),
        ),
    ]
