# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0010_auto_20170831_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitytests',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate'),
        ),
    ]
