# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 10:32
from __future__ import unicode_literals

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_candidate_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='statenursingcouncil',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.StateNursingCouncil.media_path),
        ),
    ]
