# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0011_eligibilitytests_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationalQualification',
            new_name='EducationalQualifications',
        ),
    ]
