# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_statenursingcouncil_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitytests',
            name='score_grade_marks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
