# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_eligibilitytests_score_grade_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eligibilitytests',
            name='country',
        ),
        migrations.AlterField(
            model_name='eligibilitytests',
            name='eligibility_tests',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
