# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-22 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0014_auto_20170922_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statenursingcouncil',
            name='course',
            field=models.CharField(blank=True, choices=[('ANM', 'ANM'), ('GNM', 'GNM'), ('BSc.(N)', 'BSc.(N)'), ('MSc.(N)', 'MSc.(N)')], max_length=10),
        ),
    ]
