# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 11:12
from __future__ import unicode_literals

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_auto_20171024_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='registration_number',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', editable=False, min_length=7, null=True),
        ),
    ]
