# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 04:02
from __future__ import unicode_literals

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_auto_20171024_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photograph',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Candidate.media_path),
        ),
    ]
