# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 09:34
from __future__ import unicode_literals

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_auto_20171120_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='registration_number',
            field=hashid_field.field.HashidField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', default=None, editable=False, min_length=7, null=True),
        ),
    ]
