# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0023_auto_20171120_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='sent_email_notification_provisional_registration_number',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
