# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 14:33
from __future__ import unicode_literals

import candidate.models
from django.db import migrations, models
import tnai.validators


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_candidate_sent_email_notification_provisional_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='curriculum_vitae',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Candidate.media_path, validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='photograph',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Candidate.media_path, validators=[tnai.validators.ValidateFileExtension.validate_image]),
        ),
    ]
