# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-20 14:36
from __future__ import unicode_literals

import candidate.models
from django.db import migrations, models
import tnai.validators


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0025_auto_20171120_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalqualifications',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Qualifications.media_path, validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
        migrations.AlterField(
            model_name='educationalqualifications',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Qualifications.media_path, validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
        migrations.AlterField(
            model_name='eligibilitytests',
            name='eligibility_proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.EligibilityTests.media_path, validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
        migrations.AlterField(
            model_name='experience',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Experience.media_path, validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
        migrations.AlterField(
            model_name='professionalqualifications',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.Qualifications.media_path, validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
        migrations.AlterField(
            model_name='statenursingcouncil',
            name='proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to=candidate.models.StateNursingCouncil.media_path, validators=[tnai.validators.ValidateFileExtension.validate_file]),
        ),
    ]
