# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', hashid_field.field.HashidAutoField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', editable=False, min_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Student One', max_length=200)),
                ('username', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
