# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='9810117638', max_length=200),
        ),
    ]
