# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-14 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0008_exam_questions'),
        ('student', '0002_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question', models.PositiveSmallIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('answers_given', models.ManyToManyField(to='instructor.Answer')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_taken', to='instructor.Exam', unique=True)),
            ],
        ),
    ]
