# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 12:14
from __future__ import unicode_literals

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20180909_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeexam',
            name='take_exam_id',
            field=hashid_field.field.HashidField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', default=None, editable=False, min_length=7, null=True),
        ),
    ]
