# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_takeexam_take_exam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_taken', to='instructor.Exam'),
        ),
    ]
