# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180912_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeexam',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_student', to='student.Student'),
        ),
    ]
