# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ra',
            name='logged_in_as',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_as', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
