# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0023_auto_20171220_0851'),
        ('candidate', '0030_candidate_is_active'),
        ('exam', '0010_auto_20171121_1026'),
        ('ra', '0003_auto_20171206_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_created', models.DateTimeField(default=datetime.datetime.now)),
                ('notes', models.CharField(max_length=500)),
                ('advertisement', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.Advertisement')),
                ('employer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employer.Employer')),
                ('exam', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
                ('members', models.ManyToManyField(to='candidate.Candidate')),
            ],
        ),
    ]
