# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 12:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0005_auto_20171222_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatelist',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='candidatelist',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
