# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0007_candidatelist_exam_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatelist',
            name='notes',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
